import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MyAnimeListAuthProvider } from "./providers";
import { getUser } from "@animelist/auth-next/server";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getUser(cookies());

  return (
    <html lang="en">
      <body className={inter.className}>
        <MyAnimeListAuthProvider session={session}>
          {children}
        </MyAnimeListAuthProvider>
      </body>
    </html>
  );
}
