import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MyAnimeListAuthProvider } from "./providers";
import { getServerSession } from "@animelist/auth-next/server";
import { cookies } from "next/headers";
import { MALClient } from "@animelist/client";
import { type Session } from "@animelist/auth-next/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession({
    get: (name) => cookies().get(name)?.value,
    delete: () => {},
    set: () => {},
  });

  let initialSession: Session | undefined = undefined;
  if (session) {
    const client = new MALClient({ accessToken: session.accessToken });
    const user = await client.getMyUserInfo();
    initialSession = {
      accessToken: session.accessToken,
      user,
    };
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <MyAnimeListAuthProvider session={initialSession}>
          {children}
        </MyAnimeListAuthProvider>
      </body>
    </html>
  );
}
